import Parser from 'rss-parser';
import type { FeedItem } from '@/types';

const parser = new Parser({
  timeout: 10000,
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
});

export interface RSSFetcherConfig {
  url: string;
  sourceName: string;
  icon?: string;
}

// Fetch RSS feed and convert to FeedItem format
export async function fetchRSS(config: RSSFetcherConfig): Promise<FeedItem[]> {
  try {
    const feed = await parser.parseURL(config.url);
    const items: FeedItem[] = [];

    for (const item of feed.items) {
      if (!item.title) continue;

      // Extract publish date
      let publishTime = new Date();
      if (item.pubDate) {
        publishTime = new Date(item.pubDate);
      } else if (item.isoDate) {
        publishTime = new Date(item.isoDate);
      }

      // Extract summary
      let summary = '';
      if (item.contentSnippet) {
        summary = item.contentSnippet.substring(0, 300);
      } else if (item.content) {
        // Strip HTML tags and get first 300 chars
        summary = item.content.replace(/<[^>]*>/g, '').substring(0, 300);
      } else if (item.summary) {
        summary = item.summary.substring(0, 300);
      }

      // Extract tags/categories
      const tags: string[] = [];
      if (item.categories) {
        tags.push(...item.categories);
      }

      items.push({
        id: '', // Will be generated by feed-service
        source: 'rss',
        sourceName: config.sourceName,
        title: item.title,
        summary: summary || item.title,
        url: item.link,
        publishTime,
        read: false,
        tags: tags.length > 0 ? tags : undefined,
        createdAt: new Date(),
      });
    }

    return items;
  } catch (error) {
    console.error(`Failed to fetch RSS from ${config.url}:`, error);
    return [];
  }
}

// Fetch multiple RSS feeds
export async function fetchMultipleRSS(configs: RSSFetcherConfig[]): Promise<FeedItem[]> {
  const results = await Promise.allSettled(configs.map((config) => fetchRSS(config)));

  const allItems: FeedItem[] = [];
  for (const result of results) {
    if (result.status === 'fulfilled') {
      allItems.push(...result.value);
    }
  }

  return allItems;
}

// Validate RSS feed URL
export async function validateRSSUrl(url: string): Promise<boolean> {
  try {
    await parser.parseURL(url);
    return true;
  } catch {
    return false;
  }
}

// Get RSS feed metadata
export async function getRSSMetadata(url: string): Promise<{
  title?: string;
  description?: string;
  link?: string;
} | null> {
  try {
    const feed = await parser.parseURL(url);
    return {
      title: feed.title,
      description: feed.description,
      link: feed.link,
    };
  } catch {
    return null;
  }
}
